/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from './custom-fetch'
export interface UpdateUserDto {
  name?: string
  /** @nullable */
  image?: string | null
}

export interface PhoneSignInDto {
  phoneNumber: string
  password: string
  rememberMe?: boolean
}

export interface PhoneSendOtpDto {
  phoneNumber: string
}

export interface PhoneVerifyDto {
  /** @minLength 6 */
  code: string
  phoneNumber: string
  disableSession?: boolean
  updatePhoneNumber?: boolean
}

export interface PhoneRequestPasswordResetDto {
  phoneNumber: string
}

export interface PhoneResetPasswordDto {
  /** @minLength 6 */
  otp: string
  phoneNumber: string
  /** @minLength 8 */
  newPassword: string
}

export interface CreateParcelRequestDto {
  /** @minLength 1 */
  trackingNumber: string
  source?: string
  description?: string
}

export interface CreateParcelResponseDto {
  id: string
}

export type ParcelStatus = (typeof ParcelStatus)[keyof typeof ParcelStatus]

export const ParcelStatus = {
  left_china: 'left_china',
  cleared_customs: 'cleared_customs',
  ready_for_pickup: 'ready_for_pickup',
  picked_up: 'picked_up',
} as const

/**
 * @nullable
 */
export type GetParcelResponseDtoStatus = ParcelStatus | null

export interface GetParcelResponseDto {
  /** @nullable */
  status: GetParcelResponseDtoStatus
  id: string
  createdAt: string
  updatedAt: string
  trackingNumber: string
  /** @nullable */
  userId: string | null
  /** @nullable */
  source: string | null
  /** @nullable */
  description: string | null
  /** @nullable */
  weightKg: string | null
  /** @nullable */
  deliveryFee: string | null
  /** @nullable */
  notes: string | null
}

export interface GetParcelStatusHistoryResponseDto {
  id: string
  parcelId: string
  createdAt: string
  status: ParcelStatus
}

export interface UpdateParcelRequestDto {
  /** @nullable */
  source?: string | null
  /** @nullable */
  description?: string | null
}

export interface SuccessResponseDto {
  success: boolean
}

export type GetParcelsParams = {
  status?: ParcelStatus
  search?: string
}

export const getGetHealthUrl = () => {
  return `/health`
}

export const getHealth = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getGetHealthUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetSessionUrl = () => {
  return `/auth/get-session`
}

export const getSession = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getGetSessionUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getUpdateUserUrl = () => {
  return `/auth/update-user`
}

export const updateUser = async (
  updateUserDto: UpdateUserDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getUpdateUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserDto),
  })
}

export const getSignInPhoneNumberUrl = () => {
  return `/auth/sign-in/phone-number`
}

export const signInPhoneNumber = async (
  phoneSignInDto: PhoneSignInDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getSignInPhoneNumberUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneSignInDto),
  })
}

export const getSendOtpUrl = () => {
  return `/auth/phone-number/send-otp`
}

export const sendOtp = async (
  phoneSendOtpDto: PhoneSendOtpDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getSendOtpUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneSendOtpDto),
  })
}

export const getVerifyPhoneNumberUrl = () => {
  return `/auth/phone-number/verify`
}

export const verifyPhoneNumber = async (
  phoneVerifyDto: PhoneVerifyDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getVerifyPhoneNumberUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneVerifyDto),
  })
}

export const getRequestPhonePasswordResetUrl = () => {
  return `/auth/phone-number/request-password-reset`
}

export const requestPhonePasswordReset = async (
  phoneRequestPasswordResetDto: PhoneRequestPasswordResetDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getRequestPhonePasswordResetUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneRequestPasswordResetDto),
  })
}

export const getResetPhonePasswordUrl = () => {
  return `/auth/phone-number/reset-password`
}

export const resetPhonePassword = async (
  phoneResetPasswordDto: PhoneResetPasswordDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getResetPhonePasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneResetPasswordDto),
  })
}

export const getSignOutUrl = () => {
  return `/auth/sign-out`
}

export const signOut = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getSignOutUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getCreateParcelUrl = () => {
  return `/parcels`
}

export const createParcel = async (
  createParcelRequestDto: CreateParcelRequestDto,
  options?: RequestInit
): Promise<CreateParcelResponseDto> => {
  return customFetch<CreateParcelResponseDto>(getCreateParcelUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createParcelRequestDto),
  })
}

export const getGetParcelsUrl = (params?: GetParcelsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/parcels?${stringifiedParams}`
    : `/parcels`
}

export const getParcels = async (
  params?: GetParcelsParams,
  options?: RequestInit
): Promise<GetParcelResponseDto[]> => {
  return customFetch<GetParcelResponseDto[]>(getGetParcelsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetParcelUrl = (parcelId: string) => {
  return `/parcels/${parcelId}`
}

export const getParcel = async (
  parcelId: string,
  options?: RequestInit
): Promise<GetParcelResponseDto> => {
  return customFetch<GetParcelResponseDto>(getGetParcelUrl(parcelId), {
    ...options,
    method: 'GET',
  })
}

export const getUpdateParcelUrl = (parcelId: string) => {
  return `/parcels/${parcelId}`
}

export const updateParcel = async (
  parcelId: string,
  updateParcelRequestDto: UpdateParcelRequestDto,
  options?: RequestInit
): Promise<SuccessResponseDto> => {
  return customFetch<SuccessResponseDto>(getUpdateParcelUrl(parcelId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateParcelRequestDto),
  })
}

export const getDeleteParcelUrl = (parcelId: string) => {
  return `/parcels/${parcelId}`
}

export const deleteParcel = async (
  parcelId: string,
  options?: RequestInit
): Promise<SuccessResponseDto> => {
  return customFetch<SuccessResponseDto>(getDeleteParcelUrl(parcelId), {
    ...options,
    method: 'DELETE',
  })
}

export const getGetParcelStatusHistoryUrl = (parcelId: string) => {
  return `/parcels/${parcelId}/status-history`
}

export const getParcelStatusHistory = async (
  parcelId: string,
  options?: RequestInit
): Promise<GetParcelStatusHistoryResponseDto[]> => {
  return customFetch<GetParcelStatusHistoryResponseDto[]>(
    getGetParcelStatusHistoryUrl(parcelId),
    {
      ...options,
      method: 'GET',
    }
  )
}
