/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from './custom-fetch'
export interface UpdateUserDto {
  name?: string
  /** @nullable */
  image?: string | null
}

export interface PhoneSignInDto {
  phoneNumber: string
  password: string
  rememberMe?: boolean
}

export interface PhoneSendOtpDto {
  phoneNumber: string
}

export interface PhoneVerifyDto {
  /** @minLength 6 */
  code: string
  phoneNumber: string
  disableSession?: boolean
  updatePhoneNumber?: boolean
}

export interface PhoneRequestPasswordResetDto {
  phoneNumber: string
}

export interface PhoneResetPasswordDto {
  /** @minLength 6 */
  otp: string
  phoneNumber: string
  /** @minLength 8 */
  newPassword: string
}

export interface LinkedUserDto {
  id: string
  name: string
  /** @nullable */
  phoneNumber: string | null
}

/**
 * @nullable
 */
export type GetClientResponseDtoUser = LinkedUserDto | null

export interface GetClientResponseDto {
  id: string
  code: number
  /** @nullable */
  legacyPhoneRaw: string | null
  /** @nullable */
  legacyPhoneNormalized: string | null
  /** @nullable */
  user: GetClientResponseDtoUser
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole]

export const UserRole = {
  admin: 'admin',
  client: 'client',
} as const

export interface GetUserResponseDto {
  role: UserRole
  id: string
  clientId: string
  name: string
  /** @nullable */
  phoneNumber: string | null
}

export interface CreateParcelRequestDto {
  /** @minimum 1 */
  clientCode?: number
  /**
   * @minLength 1
   * @pattern \S
   */
  trackingNumber: string
  source?: string
  description?: string
  weightKg?: string
  deliveryFee?: string
  comments?: string
}

export interface CreateParcelResponseDto {
  id: string
}

export type ParcelStatus = (typeof ParcelStatus)[keyof typeof ParcelStatus]

export const ParcelStatus = {
  left_china: 'left_china',
  cleared_customs: 'cleared_customs',
  ready_for_pickup: 'ready_for_pickup',
  picked_up: 'picked_up',
} as const

/**
 * @nullable
 */
export type GetParcelResponseDtoStatus = ParcelStatus | null

export interface GetParcelResponseDto {
  /** @nullable */
  status: GetParcelResponseDtoStatus
  id: string
  createdAt: string
  updatedAt: string
  trackingNumber: string
  clientId: string
  /** @nullable */
  source: string | null
  /** @nullable */
  description: string | null
  /** @nullable */
  weightKg: string | null
  /** @nullable */
  deliveryFee: string | null
  /** @nullable */
  comments: string | null
}

export interface GetParcelStatusHistoryResponseDto {
  status: ParcelStatus
  id: string
  parcelId: string
  createdAt: string
  achievedAt: string
}

export interface PutParcelStatusHistoryEntryRequestDto {
  status: ParcelStatus
  achievedAt: string
}

export interface PutParcelStatusHistoryRequestDto {
  entries: PutParcelStatusHistoryEntryRequestDto[]
}

export interface SuccessResponseDto {
  success: boolean
}

export interface UpdateParcelRequestDto {
  /** @nullable */
  source?: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  weightKg?: string | null
  /** @nullable */
  deliveryFee?: string | null
  /** @nullable */
  comments?: string | null
}

export interface CreateParcelsImportRequestDto {
  file: Blob
  parcelStatus: ParcelStatus
  achievedAt: string
  withHeader: string
}

export interface CreateParcelsImportResponseDto {
  id: string
}

export interface GetParcelsImportSummaryResponseDto {
  parcelStatus: ParcelStatus
  id: string
  createdAt: string
  achievedAt: string
  isCommitted: boolean
  /** @nullable */
  committedAt: string | null
}

export interface ParsedParcelsImportRowDto {
  rowNumber: number
  clientCode?: number
  trackingNumber: string
  weightKg?: number
  deliveryFee?: number
  comments?: string
}

export type ParcelsImportWarningCode =
  (typeof ParcelsImportWarningCode)[keyof typeof ParcelsImportWarningCode]

export const ParcelsImportWarningCode = {
  PARCEL_CLIENT_MISMATCH: 'PARCEL_CLIENT_MISMATCH',
  UNKNOWN_CLIENT: 'UNKNOWN_CLIENT',
} as const

export interface ParsedParcelsImportWarningDto {
  code: ParcelsImportWarningCode
  rowNumber: number
}

export type ParcelsImportErrorCode =
  (typeof ParcelsImportErrorCode)[keyof typeof ParcelsImportErrorCode]

export const ParcelsImportErrorCode = {
  CLIENT_CODE_REQUIRED: 'CLIENT_CODE_REQUIRED',
  INVALID_CLIENT_ID: 'INVALID_CLIENT_ID',
  INVALID_TRACKING_CODE: 'INVALID_TRACKING_CODE',
  INVALID_WEIGHT_KG: 'INVALID_WEIGHT_KG',
  INVALID_DELIVERY_FEE: 'INVALID_DELIVERY_FEE',
  INVALID_COMMENTS: 'INVALID_COMMENTS',
  UNKNOWN: 'UNKNOWN',
} as const

export interface ParsedParcelsImportErrorDto {
  code: ParcelsImportErrorCode
  rowNumber: number
}

export interface ParsedParcelsImportDataDto {
  rows: ParsedParcelsImportRowDto[]
  warnings: ParsedParcelsImportWarningDto[]
  errors: ParsedParcelsImportErrorDto[]
}

export interface GetParcelsImportResponseDto {
  parcelStatus: ParcelStatus
  id: string
  isCommitted: boolean
  achievedAt: string
  /** @nullable */
  committedAt: string | null
  parsedData: ParsedParcelsImportDataDto
}

export type GetClientsParams = {
  /**
   * @minimum 0
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
  search?: string
}

export type GetUsersParams = {
  /**
   * @minimum 0
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
  role?: UserRole
  search?: string
}

export type GetParcelsParams = {
  /**
   * @minimum 0
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
  status?: ParcelStatus
  search?: string
  clientId?: string
}

export type GetParcelsImportsParams = {
  /**
   * @minimum 0
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
}

export const getGetHealthUrl = () => {
  return `/health`
}

export const getHealth = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getGetHealthUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetSessionUrl = () => {
  return `/auth/get-session`
}

export const getSession = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getGetSessionUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getUpdateUserUrl = () => {
  return `/auth/update-user`
}

export const updateUser = async (
  updateUserDto: UpdateUserDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getUpdateUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserDto),
  })
}

export const getSignInPhoneNumberUrl = () => {
  return `/auth/sign-in/phone-number`
}

export const signInPhoneNumber = async (
  phoneSignInDto: PhoneSignInDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getSignInPhoneNumberUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneSignInDto),
  })
}

export const getSendOtpUrl = () => {
  return `/auth/phone-number/send-otp`
}

export const sendOtp = async (
  phoneSendOtpDto: PhoneSendOtpDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getSendOtpUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneSendOtpDto),
  })
}

export const getVerifyPhoneNumberUrl = () => {
  return `/auth/phone-number/verify`
}

export const verifyPhoneNumber = async (
  phoneVerifyDto: PhoneVerifyDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getVerifyPhoneNumberUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneVerifyDto),
  })
}

export const getRequestPhonePasswordResetUrl = () => {
  return `/auth/phone-number/request-password-reset`
}

export const requestPhonePasswordReset = async (
  phoneRequestPasswordResetDto: PhoneRequestPasswordResetDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getRequestPhonePasswordResetUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneRequestPasswordResetDto),
  })
}

export const getResetPhonePasswordUrl = () => {
  return `/auth/phone-number/reset-password`
}

export const resetPhonePassword = async (
  phoneResetPasswordDto: PhoneResetPasswordDto,
  options?: RequestInit
): Promise<void> => {
  return customFetch<void>(getResetPhonePasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneResetPasswordDto),
  })
}

export const getSignOutUrl = () => {
  return `/auth/sign-out`
}

export const signOut = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getSignOutUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getGetClientsUrl = (params?: GetClientsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/clients?${stringifiedParams}`
    : `/clients`
}

export const getClients = async (
  params?: GetClientsParams,
  options?: RequestInit
): Promise<GetClientResponseDto[]> => {
  return customFetch<GetClientResponseDto[]>(getGetClientsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetClientUrl = (clientId: string) => {
  return `/clients/${clientId}`
}

export const getClient = async (
  clientId: string,
  options?: RequestInit
): Promise<GetClientResponseDto> => {
  return customFetch<GetClientResponseDto>(getGetClientUrl(clientId), {
    ...options,
    method: 'GET',
  })
}

export const getGetUserUrl = (userId: string) => {
  return `/users/${userId}`
}

export const getUser = async (
  userId: string,
  options?: RequestInit
): Promise<GetUserResponseDto> => {
  return customFetch<GetUserResponseDto>(getGetUserUrl(userId), {
    ...options,
    method: 'GET',
  })
}

export const getGetUsersUrl = (params?: GetUsersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/users?${stringifiedParams}` : `/users`
}

export const getUsers = async (
  params?: GetUsersParams,
  options?: RequestInit
): Promise<GetUserResponseDto[]> => {
  return customFetch<GetUserResponseDto[]>(getGetUsersUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getCreateParcelUrl = () => {
  return `/parcels`
}

export const createParcel = async (
  createParcelRequestDto: CreateParcelRequestDto,
  options?: RequestInit
): Promise<CreateParcelResponseDto> => {
  return customFetch<CreateParcelResponseDto>(getCreateParcelUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createParcelRequestDto),
  })
}

export const getGetParcelsUrl = (params?: GetParcelsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/parcels?${stringifiedParams}`
    : `/parcels`
}

export const getParcels = async (
  params?: GetParcelsParams,
  options?: RequestInit
): Promise<GetParcelResponseDto[]> => {
  return customFetch<GetParcelResponseDto[]>(getGetParcelsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetParcelUrl = (parcelId: string) => {
  return `/parcels/${parcelId}`
}

export const getParcel = async (
  parcelId: string,
  options?: RequestInit
): Promise<GetParcelResponseDto> => {
  return customFetch<GetParcelResponseDto>(getGetParcelUrl(parcelId), {
    ...options,
    method: 'GET',
  })
}

export const getUpdateParcelUrl = (parcelId: string) => {
  return `/parcels/${parcelId}`
}

export const updateParcel = async (
  parcelId: string,
  updateParcelRequestDto: UpdateParcelRequestDto,
  options?: RequestInit
): Promise<SuccessResponseDto> => {
  return customFetch<SuccessResponseDto>(getUpdateParcelUrl(parcelId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateParcelRequestDto),
  })
}

export const getDeleteParcelUrl = (parcelId: string) => {
  return `/parcels/${parcelId}`
}

export const deleteParcel = async (
  parcelId: string,
  options?: RequestInit
): Promise<SuccessResponseDto> => {
  return customFetch<SuccessResponseDto>(getDeleteParcelUrl(parcelId), {
    ...options,
    method: 'DELETE',
  })
}

export const getGetParcelStatusHistoryUrl = (parcelId: string) => {
  return `/parcels/${parcelId}/status-history`
}

export const getParcelStatusHistory = async (
  parcelId: string,
  options?: RequestInit
): Promise<GetParcelStatusHistoryResponseDto[]> => {
  return customFetch<GetParcelStatusHistoryResponseDto[]>(
    getGetParcelStatusHistoryUrl(parcelId),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getPutParcelStatusHistoryUrl = (parcelId: string) => {
  return `/parcels/${parcelId}/status-history`
}

export const putParcelStatusHistory = async (
  parcelId: string,
  putParcelStatusHistoryRequestDto: PutParcelStatusHistoryRequestDto,
  options?: RequestInit
): Promise<SuccessResponseDto> => {
  return customFetch<SuccessResponseDto>(
    getPutParcelStatusHistoryUrl(parcelId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(putParcelStatusHistoryRequestDto),
    }
  )
}

export const getCreateParcelsImportUrl = () => {
  return `/parcels-imports`
}

export const createParcelsImport = async (
  createParcelsImportRequestDto: CreateParcelsImportRequestDto,
  options?: RequestInit
): Promise<CreateParcelsImportResponseDto> => {
  const formData = new FormData()
  formData.append(`file`, createParcelsImportRequestDto.file)
  formData.append(`parcelStatus`, createParcelsImportRequestDto.parcelStatus)
  formData.append(`achievedAt`, createParcelsImportRequestDto.achievedAt)
  formData.append(`withHeader`, createParcelsImportRequestDto.withHeader)

  return customFetch<CreateParcelsImportResponseDto>(
    getCreateParcelsImportUrl(),
    {
      ...options,
      method: 'POST',
      body: formData,
    }
  )
}

export const getGetParcelsImportsUrl = (params?: GetParcelsImportsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/parcels-imports?${stringifiedParams}`
    : `/parcels-imports`
}

export const getParcelsImports = async (
  params?: GetParcelsImportsParams,
  options?: RequestInit
): Promise<GetParcelsImportSummaryResponseDto[]> => {
  return customFetch<GetParcelsImportSummaryResponseDto[]>(
    getGetParcelsImportsUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getCommitParcelsImportUrl = (parcelsImportId: string) => {
  return `/parcels-imports/${parcelsImportId}`
}

export const commitParcelsImport = async (
  parcelsImportId: string,
  options?: RequestInit
): Promise<SuccessResponseDto> => {
  return customFetch<SuccessResponseDto>(
    getCommitParcelsImportUrl(parcelsImportId),
    {
      ...options,
      method: 'POST',
    }
  )
}

export const getGetParcelsImportUrl = (parcelsImportId: string) => {
  return `/parcels-imports/${parcelsImportId}`
}

export const getParcelsImport = async (
  parcelsImportId: string,
  options?: RequestInit
): Promise<GetParcelsImportResponseDto> => {
  return customFetch<GetParcelsImportResponseDto>(
    getGetParcelsImportUrl(parcelsImportId),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getDeleteParcelsImportUrl = (parcelsImportId: string) => {
  return `/parcels-imports/${parcelsImportId}`
}

export const deleteParcelsImport = async (
  parcelsImportId: string,
  options?: RequestInit
): Promise<SuccessResponseDto> => {
  return customFetch<SuccessResponseDto>(
    getDeleteParcelsImportUrl(parcelsImportId),
    {
      ...options,
      method: 'DELETE',
    }
  )
}
