/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedClientRouteRouteImport } from './routes/_authenticated/_client/route'
import { Route as AuthenticatedClientProfileIndexRouteImport } from './routes/_authenticated/_client/profile/index'
import { Route as AuthenticatedClientParcelsIndexRouteImport } from './routes/_authenticated/_client/parcels/index'
import { Route as AuthenticatedClientAddressIndexRouteImport } from './routes/_authenticated/_client/address/index'
import { Route as AuthenticatedClientProfileEditRouteImport } from './routes/_authenticated/_client/profile/edit'
import { Route as AuthenticatedClientParcelsAddRouteImport } from './routes/_authenticated/_client/parcels/add'
import { Route as AuthenticatedClientParcelsParcelIdIndexRouteImport } from './routes/_authenticated/_client/parcels/$parcelId/index'
import { Route as AuthenticatedClientParcelsParcelIdEditRouteImport } from './routes/_authenticated/_client/parcels/$parcelId/edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRouteRoute =
  AuthenticatedClientRouteRouteImport.update({
    id: '/_client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientProfileIndexRoute =
  AuthenticatedClientProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientParcelsIndexRoute =
  AuthenticatedClientParcelsIndexRouteImport.update({
    id: '/parcels/',
    path: '/parcels/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientAddressIndexRoute =
  AuthenticatedClientAddressIndexRouteImport.update({
    id: '/address/',
    path: '/address/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientProfileEditRoute =
  AuthenticatedClientProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientParcelsAddRoute =
  AuthenticatedClientParcelsAddRouteImport.update({
    id: '/parcels/add',
    path: '/parcels/add',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientParcelsParcelIdIndexRoute =
  AuthenticatedClientParcelsParcelIdIndexRouteImport.update({
    id: '/parcels/$parcelId/',
    path: '/parcels/$parcelId/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientParcelsParcelIdEditRoute =
  AuthenticatedClientParcelsParcelIdEditRouteImport.update({
    id: '/parcels/$parcelId/edit',
    path: '/parcels/$parcelId/edit',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/parcels/add': typeof AuthenticatedClientParcelsAddRoute
  '/profile/edit': typeof AuthenticatedClientProfileEditRoute
  '/address/': typeof AuthenticatedClientAddressIndexRoute
  '/parcels/': typeof AuthenticatedClientParcelsIndexRoute
  '/profile/': typeof AuthenticatedClientProfileIndexRoute
  '/parcels/$parcelId/edit': typeof AuthenticatedClientParcelsParcelIdEditRoute
  '/parcels/$parcelId/': typeof AuthenticatedClientParcelsParcelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/parcels/add': typeof AuthenticatedClientParcelsAddRoute
  '/profile/edit': typeof AuthenticatedClientProfileEditRoute
  '/address': typeof AuthenticatedClientAddressIndexRoute
  '/parcels': typeof AuthenticatedClientParcelsIndexRoute
  '/profile': typeof AuthenticatedClientProfileIndexRoute
  '/parcels/$parcelId/edit': typeof AuthenticatedClientParcelsParcelIdEditRoute
  '/parcels/$parcelId': typeof AuthenticatedClientParcelsParcelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/_client': typeof AuthenticatedClientRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/_client/parcels/add': typeof AuthenticatedClientParcelsAddRoute
  '/_authenticated/_client/profile/edit': typeof AuthenticatedClientProfileEditRoute
  '/_authenticated/_client/address/': typeof AuthenticatedClientAddressIndexRoute
  '/_authenticated/_client/parcels/': typeof AuthenticatedClientParcelsIndexRoute
  '/_authenticated/_client/profile/': typeof AuthenticatedClientProfileIndexRoute
  '/_authenticated/_client/parcels/$parcelId/edit': typeof AuthenticatedClientParcelsParcelIdEditRoute
  '/_authenticated/_client/parcels/$parcelId/': typeof AuthenticatedClientParcelsParcelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/parcels/add'
    | '/profile/edit'
    | '/address/'
    | '/parcels/'
    | '/profile/'
    | '/parcels/$parcelId/edit'
    | '/parcels/$parcelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/parcels/add'
    | '/profile/edit'
    | '/address'
    | '/parcels'
    | '/profile'
    | '/parcels/$parcelId/edit'
    | '/parcels/$parcelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_client'
    | '/_authenticated/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/_authenticated/_client/parcels/add'
    | '/_authenticated/_client/profile/edit'
    | '/_authenticated/_client/address/'
    | '/_authenticated/_client/parcels/'
    | '/_authenticated/_client/profile/'
    | '/_authenticated/_client/parcels/$parcelId/edit'
    | '/_authenticated/_client/parcels/$parcelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_client': {
      id: '/_authenticated/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClientRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_client/profile/': {
      id: '/_authenticated/_client/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedClientProfileIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/parcels/': {
      id: '/_authenticated/_client/parcels/'
      path: '/parcels'
      fullPath: '/parcels/'
      preLoaderRoute: typeof AuthenticatedClientParcelsIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/address/': {
      id: '/_authenticated/_client/address/'
      path: '/address'
      fullPath: '/address/'
      preLoaderRoute: typeof AuthenticatedClientAddressIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/profile/edit': {
      id: '/_authenticated/_client/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedClientProfileEditRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/parcels/add': {
      id: '/_authenticated/_client/parcels/add'
      path: '/parcels/add'
      fullPath: '/parcels/add'
      preLoaderRoute: typeof AuthenticatedClientParcelsAddRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/parcels/$parcelId/': {
      id: '/_authenticated/_client/parcels/$parcelId/'
      path: '/parcels/$parcelId'
      fullPath: '/parcels/$parcelId/'
      preLoaderRoute: typeof AuthenticatedClientParcelsParcelIdIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/parcels/$parcelId/edit': {
      id: '/_authenticated/_client/parcels/$parcelId/edit'
      path: '/parcels/$parcelId/edit'
      fullPath: '/parcels/$parcelId/edit'
      preLoaderRoute: typeof AuthenticatedClientParcelsParcelIdEditRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
  }
}

interface AuthenticatedClientRouteRouteChildren {
  AuthenticatedClientParcelsAddRoute: typeof AuthenticatedClientParcelsAddRoute
  AuthenticatedClientProfileEditRoute: typeof AuthenticatedClientProfileEditRoute
  AuthenticatedClientAddressIndexRoute: typeof AuthenticatedClientAddressIndexRoute
  AuthenticatedClientParcelsIndexRoute: typeof AuthenticatedClientParcelsIndexRoute
  AuthenticatedClientProfileIndexRoute: typeof AuthenticatedClientProfileIndexRoute
  AuthenticatedClientParcelsParcelIdEditRoute: typeof AuthenticatedClientParcelsParcelIdEditRoute
  AuthenticatedClientParcelsParcelIdIndexRoute: typeof AuthenticatedClientParcelsParcelIdIndexRoute
}

const AuthenticatedClientRouteRouteChildren: AuthenticatedClientRouteRouteChildren =
  {
    AuthenticatedClientParcelsAddRoute: AuthenticatedClientParcelsAddRoute,
    AuthenticatedClientProfileEditRoute: AuthenticatedClientProfileEditRoute,
    AuthenticatedClientAddressIndexRoute: AuthenticatedClientAddressIndexRoute,
    AuthenticatedClientParcelsIndexRoute: AuthenticatedClientParcelsIndexRoute,
    AuthenticatedClientProfileIndexRoute: AuthenticatedClientProfileIndexRoute,
    AuthenticatedClientParcelsParcelIdEditRoute:
      AuthenticatedClientParcelsParcelIdEditRoute,
    AuthenticatedClientParcelsParcelIdIndexRoute:
      AuthenticatedClientParcelsParcelIdIndexRoute,
  }

const AuthenticatedClientRouteRouteWithChildren =
  AuthenticatedClientRouteRoute._addFileChildren(
    AuthenticatedClientRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientRouteRoute: typeof AuthenticatedClientRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientRouteRoute: AuthenticatedClientRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
