/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedClientRouteRouteImport } from './routes/_authenticated/_client/route'
import { Route as AuthenticatedAdminParcelsIndexRouteImport } from './routes/_authenticated/admin/parcels/index'
import { Route as AuthenticatedAdminParcelsImportsIndexRouteImport } from './routes/_authenticated/admin/parcels-imports/index'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin/clients/index'
import { Route as AuthenticatedClientTrainingIndexRouteImport } from './routes/_authenticated/_client/training/index'
import { Route as AuthenticatedClientProfileIndexRouteImport } from './routes/_authenticated/_client/profile/index'
import { Route as AuthenticatedClientParcelsIndexRouteImport } from './routes/_authenticated/_client/parcels/index'
import { Route as AuthenticatedClientAddressIndexRouteImport } from './routes/_authenticated/_client/address/index'
import { Route as AuthenticatedAdminParcelsAddRouteImport } from './routes/_authenticated/admin/parcels/add'
import { Route as AuthenticatedAdminParcelsImportsAddRouteImport } from './routes/_authenticated/admin/parcels-imports/add'
import { Route as AuthenticatedClientProfileEditRouteImport } from './routes/_authenticated/_client/profile/edit'
import { Route as AuthenticatedClientParcelsAddRouteImport } from './routes/_authenticated/_client/parcels/add'
import { Route as AuthenticatedClientAddressMarketplaceRouteImport } from './routes/_authenticated/_client/address/$marketplace'
import { Route as AuthenticatedAdminParcelsParcelIdIndexRouteImport } from './routes/_authenticated/admin/parcels/$parcelId/index'
import { Route as AuthenticatedAdminParcelsImportsParcelsImportIdIndexRouteImport } from './routes/_authenticated/admin/parcels-imports/$parcelsImportId/index'
import { Route as AuthenticatedAdminClientsClientIdIndexRouteImport } from './routes/_authenticated/admin/clients/$clientId/index'
import { Route as AuthenticatedClientParcelsParcelIdIndexRouteImport } from './routes/_authenticated/_client/parcels/$parcelId/index'
import { Route as AuthenticatedAdminParcelsParcelIdEditRouteImport } from './routes/_authenticated/admin/parcels/$parcelId/edit'
import { Route as AuthenticatedClientParcelsParcelIdEditRouteImport } from './routes/_authenticated/_client/parcels/$parcelId/edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRouteRoute =
  AuthenticatedClientRouteRouteImport.update({
    id: '/_client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminParcelsIndexRoute =
  AuthenticatedAdminParcelsIndexRouteImport.update({
    id: '/parcels/',
    path: '/parcels/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminParcelsImportsIndexRoute =
  AuthenticatedAdminParcelsImportsIndexRouteImport.update({
    id: '/parcels-imports/',
    path: '/parcels-imports/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClientTrainingIndexRoute =
  AuthenticatedClientTrainingIndexRouteImport.update({
    id: '/training/',
    path: '/training/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientProfileIndexRoute =
  AuthenticatedClientProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientParcelsIndexRoute =
  AuthenticatedClientParcelsIndexRouteImport.update({
    id: '/parcels/',
    path: '/parcels/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientAddressIndexRoute =
  AuthenticatedClientAddressIndexRouteImport.update({
    id: '/address/',
    path: '/address/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminParcelsAddRoute =
  AuthenticatedAdminParcelsAddRouteImport.update({
    id: '/parcels/add',
    path: '/parcels/add',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminParcelsImportsAddRoute =
  AuthenticatedAdminParcelsImportsAddRouteImport.update({
    id: '/parcels-imports/add',
    path: '/parcels-imports/add',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClientProfileEditRoute =
  AuthenticatedClientProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientParcelsAddRoute =
  AuthenticatedClientParcelsAddRouteImport.update({
    id: '/parcels/add',
    path: '/parcels/add',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientAddressMarketplaceRoute =
  AuthenticatedClientAddressMarketplaceRouteImport.update({
    id: '/address/$marketplace',
    path: '/address/$marketplace',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminParcelsParcelIdIndexRoute =
  AuthenticatedAdminParcelsParcelIdIndexRouteImport.update({
    id: '/parcels/$parcelId/',
    path: '/parcels/$parcelId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminParcelsImportsParcelsImportIdIndexRoute =
  AuthenticatedAdminParcelsImportsParcelsImportIdIndexRouteImport.update({
    id: '/parcels-imports/$parcelsImportId/',
    path: '/parcels-imports/$parcelsImportId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsClientIdIndexRoute =
  AuthenticatedAdminClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClientParcelsParcelIdIndexRoute =
  AuthenticatedClientParcelsParcelIdIndexRouteImport.update({
    id: '/parcels/$parcelId/',
    path: '/parcels/$parcelId/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminParcelsParcelIdEditRoute =
  AuthenticatedAdminParcelsParcelIdEditRouteImport.update({
    id: '/parcels/$parcelId/edit',
    path: '/parcels/$parcelId/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClientParcelsParcelIdEditRoute =
  AuthenticatedClientParcelsParcelIdEditRouteImport.update({
    id: '/parcels/$parcelId/edit',
    path: '/parcels/$parcelId/edit',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/address/$marketplace': typeof AuthenticatedClientAddressMarketplaceRoute
  '/parcels/add': typeof AuthenticatedClientParcelsAddRoute
  '/profile/edit': typeof AuthenticatedClientProfileEditRoute
  '/admin/parcels-imports/add': typeof AuthenticatedAdminParcelsImportsAddRoute
  '/admin/parcels/add': typeof AuthenticatedAdminParcelsAddRoute
  '/address/': typeof AuthenticatedClientAddressIndexRoute
  '/parcels/': typeof AuthenticatedClientParcelsIndexRoute
  '/profile/': typeof AuthenticatedClientProfileIndexRoute
  '/training/': typeof AuthenticatedClientTrainingIndexRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/parcels-imports/': typeof AuthenticatedAdminParcelsImportsIndexRoute
  '/admin/parcels/': typeof AuthenticatedAdminParcelsIndexRoute
  '/parcels/$parcelId/edit': typeof AuthenticatedClientParcelsParcelIdEditRoute
  '/admin/parcels/$parcelId/edit': typeof AuthenticatedAdminParcelsParcelIdEditRoute
  '/parcels/$parcelId/': typeof AuthenticatedClientParcelsParcelIdIndexRoute
  '/admin/clients/$clientId/': typeof AuthenticatedAdminClientsClientIdIndexRoute
  '/admin/parcels-imports/$parcelsImportId/': typeof AuthenticatedAdminParcelsImportsParcelsImportIdIndexRoute
  '/admin/parcels/$parcelId/': typeof AuthenticatedAdminParcelsParcelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/address/$marketplace': typeof AuthenticatedClientAddressMarketplaceRoute
  '/parcels/add': typeof AuthenticatedClientParcelsAddRoute
  '/profile/edit': typeof AuthenticatedClientProfileEditRoute
  '/admin/parcels-imports/add': typeof AuthenticatedAdminParcelsImportsAddRoute
  '/admin/parcels/add': typeof AuthenticatedAdminParcelsAddRoute
  '/address': typeof AuthenticatedClientAddressIndexRoute
  '/parcels': typeof AuthenticatedClientParcelsIndexRoute
  '/profile': typeof AuthenticatedClientProfileIndexRoute
  '/training': typeof AuthenticatedClientTrainingIndexRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/parcels-imports': typeof AuthenticatedAdminParcelsImportsIndexRoute
  '/admin/parcels': typeof AuthenticatedAdminParcelsIndexRoute
  '/parcels/$parcelId/edit': typeof AuthenticatedClientParcelsParcelIdEditRoute
  '/admin/parcels/$parcelId/edit': typeof AuthenticatedAdminParcelsParcelIdEditRoute
  '/parcels/$parcelId': typeof AuthenticatedClientParcelsParcelIdIndexRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdIndexRoute
  '/admin/parcels-imports/$parcelsImportId': typeof AuthenticatedAdminParcelsImportsParcelsImportIdIndexRoute
  '/admin/parcels/$parcelId': typeof AuthenticatedAdminParcelsParcelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/_client': typeof AuthenticatedClientRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/_client/address/$marketplace': typeof AuthenticatedClientAddressMarketplaceRoute
  '/_authenticated/_client/parcels/add': typeof AuthenticatedClientParcelsAddRoute
  '/_authenticated/_client/profile/edit': typeof AuthenticatedClientProfileEditRoute
  '/_authenticated/admin/parcels-imports/add': typeof AuthenticatedAdminParcelsImportsAddRoute
  '/_authenticated/admin/parcels/add': typeof AuthenticatedAdminParcelsAddRoute
  '/_authenticated/_client/address/': typeof AuthenticatedClientAddressIndexRoute
  '/_authenticated/_client/parcels/': typeof AuthenticatedClientParcelsIndexRoute
  '/_authenticated/_client/profile/': typeof AuthenticatedClientProfileIndexRoute
  '/_authenticated/_client/training/': typeof AuthenticatedClientTrainingIndexRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/parcels-imports/': typeof AuthenticatedAdminParcelsImportsIndexRoute
  '/_authenticated/admin/parcels/': typeof AuthenticatedAdminParcelsIndexRoute
  '/_authenticated/_client/parcels/$parcelId/edit': typeof AuthenticatedClientParcelsParcelIdEditRoute
  '/_authenticated/admin/parcels/$parcelId/edit': typeof AuthenticatedAdminParcelsParcelIdEditRoute
  '/_authenticated/_client/parcels/$parcelId/': typeof AuthenticatedClientParcelsParcelIdIndexRoute
  '/_authenticated/admin/clients/$clientId/': typeof AuthenticatedAdminClientsClientIdIndexRoute
  '/_authenticated/admin/parcels-imports/$parcelsImportId/': typeof AuthenticatedAdminParcelsImportsParcelsImportIdIndexRoute
  '/_authenticated/admin/parcels/$parcelId/': typeof AuthenticatedAdminParcelsParcelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/address/$marketplace'
    | '/parcels/add'
    | '/profile/edit'
    | '/admin/parcels-imports/add'
    | '/admin/parcels/add'
    | '/address/'
    | '/parcels/'
    | '/profile/'
    | '/training/'
    | '/admin/clients/'
    | '/admin/parcels-imports/'
    | '/admin/parcels/'
    | '/parcels/$parcelId/edit'
    | '/admin/parcels/$parcelId/edit'
    | '/parcels/$parcelId/'
    | '/admin/clients/$clientId/'
    | '/admin/parcels-imports/$parcelsImportId/'
    | '/admin/parcels/$parcelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/address/$marketplace'
    | '/parcels/add'
    | '/profile/edit'
    | '/admin/parcels-imports/add'
    | '/admin/parcels/add'
    | '/address'
    | '/parcels'
    | '/profile'
    | '/training'
    | '/admin/clients'
    | '/admin/parcels-imports'
    | '/admin/parcels'
    | '/parcels/$parcelId/edit'
    | '/admin/parcels/$parcelId/edit'
    | '/parcels/$parcelId'
    | '/admin/clients/$clientId'
    | '/admin/parcels-imports/$parcelsImportId'
    | '/admin/parcels/$parcelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_client'
    | '/_authenticated/admin'
    | '/_authenticated/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/_authenticated/_client/address/$marketplace'
    | '/_authenticated/_client/parcels/add'
    | '/_authenticated/_client/profile/edit'
    | '/_authenticated/admin/parcels-imports/add'
    | '/_authenticated/admin/parcels/add'
    | '/_authenticated/_client/address/'
    | '/_authenticated/_client/parcels/'
    | '/_authenticated/_client/profile/'
    | '/_authenticated/_client/training/'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/parcels-imports/'
    | '/_authenticated/admin/parcels/'
    | '/_authenticated/_client/parcels/$parcelId/edit'
    | '/_authenticated/admin/parcels/$parcelId/edit'
    | '/_authenticated/_client/parcels/$parcelId/'
    | '/_authenticated/admin/clients/$clientId/'
    | '/_authenticated/admin/parcels-imports/$parcelsImportId/'
    | '/_authenticated/admin/parcels/$parcelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_client': {
      id: '/_authenticated/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClientRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/parcels/': {
      id: '/_authenticated/admin/parcels/'
      path: '/parcels'
      fullPath: '/admin/parcels/'
      preLoaderRoute: typeof AuthenticatedAdminParcelsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/parcels-imports/': {
      id: '/_authenticated/admin/parcels-imports/'
      path: '/parcels-imports'
      fullPath: '/admin/parcels-imports/'
      preLoaderRoute: typeof AuthenticatedAdminParcelsImportsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_client/training/': {
      id: '/_authenticated/_client/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof AuthenticatedClientTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/profile/': {
      id: '/_authenticated/_client/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedClientProfileIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/parcels/': {
      id: '/_authenticated/_client/parcels/'
      path: '/parcels'
      fullPath: '/parcels/'
      preLoaderRoute: typeof AuthenticatedClientParcelsIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/address/': {
      id: '/_authenticated/_client/address/'
      path: '/address'
      fullPath: '/address/'
      preLoaderRoute: typeof AuthenticatedClientAddressIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/parcels/add': {
      id: '/_authenticated/admin/parcels/add'
      path: '/parcels/add'
      fullPath: '/admin/parcels/add'
      preLoaderRoute: typeof AuthenticatedAdminParcelsAddRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/parcels-imports/add': {
      id: '/_authenticated/admin/parcels-imports/add'
      path: '/parcels-imports/add'
      fullPath: '/admin/parcels-imports/add'
      preLoaderRoute: typeof AuthenticatedAdminParcelsImportsAddRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_client/profile/edit': {
      id: '/_authenticated/_client/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedClientProfileEditRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/parcels/add': {
      id: '/_authenticated/_client/parcels/add'
      path: '/parcels/add'
      fullPath: '/parcels/add'
      preLoaderRoute: typeof AuthenticatedClientParcelsAddRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/_client/address/$marketplace': {
      id: '/_authenticated/_client/address/$marketplace'
      path: '/address/$marketplace'
      fullPath: '/address/$marketplace'
      preLoaderRoute: typeof AuthenticatedClientAddressMarketplaceRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/parcels/$parcelId/': {
      id: '/_authenticated/admin/parcels/$parcelId/'
      path: '/parcels/$parcelId'
      fullPath: '/admin/parcels/$parcelId/'
      preLoaderRoute: typeof AuthenticatedAdminParcelsParcelIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/parcels-imports/$parcelsImportId/': {
      id: '/_authenticated/admin/parcels-imports/$parcelsImportId/'
      path: '/parcels-imports/$parcelsImportId'
      fullPath: '/admin/parcels-imports/$parcelsImportId/'
      preLoaderRoute: typeof AuthenticatedAdminParcelsImportsParcelsImportIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/$clientId/': {
      id: '/_authenticated/admin/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId/'
      preLoaderRoute: typeof AuthenticatedAdminClientsClientIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_client/parcels/$parcelId/': {
      id: '/_authenticated/_client/parcels/$parcelId/'
      path: '/parcels/$parcelId'
      fullPath: '/parcels/$parcelId/'
      preLoaderRoute: typeof AuthenticatedClientParcelsParcelIdIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/parcels/$parcelId/edit': {
      id: '/_authenticated/admin/parcels/$parcelId/edit'
      path: '/parcels/$parcelId/edit'
      fullPath: '/admin/parcels/$parcelId/edit'
      preLoaderRoute: typeof AuthenticatedAdminParcelsParcelIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_client/parcels/$parcelId/edit': {
      id: '/_authenticated/_client/parcels/$parcelId/edit'
      path: '/parcels/$parcelId/edit'
      fullPath: '/parcels/$parcelId/edit'
      preLoaderRoute: typeof AuthenticatedClientParcelsParcelIdEditRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
  }
}

interface AuthenticatedClientRouteRouteChildren {
  AuthenticatedClientAddressMarketplaceRoute: typeof AuthenticatedClientAddressMarketplaceRoute
  AuthenticatedClientParcelsAddRoute: typeof AuthenticatedClientParcelsAddRoute
  AuthenticatedClientProfileEditRoute: typeof AuthenticatedClientProfileEditRoute
  AuthenticatedClientAddressIndexRoute: typeof AuthenticatedClientAddressIndexRoute
  AuthenticatedClientParcelsIndexRoute: typeof AuthenticatedClientParcelsIndexRoute
  AuthenticatedClientProfileIndexRoute: typeof AuthenticatedClientProfileIndexRoute
  AuthenticatedClientTrainingIndexRoute: typeof AuthenticatedClientTrainingIndexRoute
  AuthenticatedClientParcelsParcelIdEditRoute: typeof AuthenticatedClientParcelsParcelIdEditRoute
  AuthenticatedClientParcelsParcelIdIndexRoute: typeof AuthenticatedClientParcelsParcelIdIndexRoute
}

const AuthenticatedClientRouteRouteChildren: AuthenticatedClientRouteRouteChildren =
  {
    AuthenticatedClientAddressMarketplaceRoute:
      AuthenticatedClientAddressMarketplaceRoute,
    AuthenticatedClientParcelsAddRoute: AuthenticatedClientParcelsAddRoute,
    AuthenticatedClientProfileEditRoute: AuthenticatedClientProfileEditRoute,
    AuthenticatedClientAddressIndexRoute: AuthenticatedClientAddressIndexRoute,
    AuthenticatedClientParcelsIndexRoute: AuthenticatedClientParcelsIndexRoute,
    AuthenticatedClientProfileIndexRoute: AuthenticatedClientProfileIndexRoute,
    AuthenticatedClientTrainingIndexRoute:
      AuthenticatedClientTrainingIndexRoute,
    AuthenticatedClientParcelsParcelIdEditRoute:
      AuthenticatedClientParcelsParcelIdEditRoute,
    AuthenticatedClientParcelsParcelIdIndexRoute:
      AuthenticatedClientParcelsParcelIdIndexRoute,
  }

const AuthenticatedClientRouteRouteWithChildren =
  AuthenticatedClientRouteRoute._addFileChildren(
    AuthenticatedClientRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminParcelsImportsAddRoute: typeof AuthenticatedAdminParcelsImportsAddRoute
  AuthenticatedAdminParcelsAddRoute: typeof AuthenticatedAdminParcelsAddRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
  AuthenticatedAdminParcelsImportsIndexRoute: typeof AuthenticatedAdminParcelsImportsIndexRoute
  AuthenticatedAdminParcelsIndexRoute: typeof AuthenticatedAdminParcelsIndexRoute
  AuthenticatedAdminParcelsParcelIdEditRoute: typeof AuthenticatedAdminParcelsParcelIdEditRoute
  AuthenticatedAdminClientsClientIdIndexRoute: typeof AuthenticatedAdminClientsClientIdIndexRoute
  AuthenticatedAdminParcelsImportsParcelsImportIdIndexRoute: typeof AuthenticatedAdminParcelsImportsParcelsImportIdIndexRoute
  AuthenticatedAdminParcelsParcelIdIndexRoute: typeof AuthenticatedAdminParcelsParcelIdIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminParcelsImportsAddRoute:
      AuthenticatedAdminParcelsImportsAddRoute,
    AuthenticatedAdminParcelsAddRoute: AuthenticatedAdminParcelsAddRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
    AuthenticatedAdminParcelsImportsIndexRoute:
      AuthenticatedAdminParcelsImportsIndexRoute,
    AuthenticatedAdminParcelsIndexRoute: AuthenticatedAdminParcelsIndexRoute,
    AuthenticatedAdminParcelsParcelIdEditRoute:
      AuthenticatedAdminParcelsParcelIdEditRoute,
    AuthenticatedAdminClientsClientIdIndexRoute:
      AuthenticatedAdminClientsClientIdIndexRoute,
    AuthenticatedAdminParcelsImportsParcelsImportIdIndexRoute:
      AuthenticatedAdminParcelsImportsParcelsImportIdIndexRoute,
    AuthenticatedAdminParcelsParcelIdIndexRoute:
      AuthenticatedAdminParcelsParcelIdIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientRouteRoute: typeof AuthenticatedClientRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientRouteRoute: AuthenticatedClientRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
