/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMenuRouteRouteImport } from './routes/_authenticated/_menu/route'
import { Route as AuthenticatedMenuProfileIndexRouteImport } from './routes/_authenticated/_menu/profile/index'
import { Route as AuthenticatedMenuParcelsIndexRouteImport } from './routes/_authenticated/_menu/parcels/index'
import { Route as AuthenticatedMenuAddressIndexRouteImport } from './routes/_authenticated/_menu/address/index'
import { Route as AuthenticatedMenuProfileEditRouteImport } from './routes/_authenticated/_menu/profile/edit'
import { Route as AuthenticatedMenuParcelsAddRouteImport } from './routes/_authenticated/_menu/parcels/add'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRouteRoute = AuthenticatedMenuRouteRouteImport.update({
  id: '/_menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuProfileIndexRoute =
  AuthenticatedMenuProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedMenuRouteRoute,
  } as any)
const AuthenticatedMenuParcelsIndexRoute =
  AuthenticatedMenuParcelsIndexRouteImport.update({
    id: '/parcels/',
    path: '/parcels/',
    getParentRoute: () => AuthenticatedMenuRouteRoute,
  } as any)
const AuthenticatedMenuAddressIndexRoute =
  AuthenticatedMenuAddressIndexRouteImport.update({
    id: '/address/',
    path: '/address/',
    getParentRoute: () => AuthenticatedMenuRouteRoute,
  } as any)
const AuthenticatedMenuProfileEditRoute =
  AuthenticatedMenuProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedMenuRouteRoute,
  } as any)
const AuthenticatedMenuParcelsAddRoute =
  AuthenticatedMenuParcelsAddRouteImport.update({
    id: '/parcels/add',
    path: '/parcels/add',
    getParentRoute: () => AuthenticatedMenuRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/parcels/add': typeof AuthenticatedMenuParcelsAddRoute
  '/profile/edit': typeof AuthenticatedMenuProfileEditRoute
  '/address/': typeof AuthenticatedMenuAddressIndexRoute
  '/parcels/': typeof AuthenticatedMenuParcelsIndexRoute
  '/profile/': typeof AuthenticatedMenuProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/parcels/add': typeof AuthenticatedMenuParcelsAddRoute
  '/profile/edit': typeof AuthenticatedMenuProfileEditRoute
  '/address': typeof AuthenticatedMenuAddressIndexRoute
  '/parcels': typeof AuthenticatedMenuParcelsIndexRoute
  '/profile': typeof AuthenticatedMenuProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/_menu': typeof AuthenticatedMenuRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/_menu/parcels/add': typeof AuthenticatedMenuParcelsAddRoute
  '/_authenticated/_menu/profile/edit': typeof AuthenticatedMenuProfileEditRoute
  '/_authenticated/_menu/address/': typeof AuthenticatedMenuAddressIndexRoute
  '/_authenticated/_menu/parcels/': typeof AuthenticatedMenuParcelsIndexRoute
  '/_authenticated/_menu/profile/': typeof AuthenticatedMenuProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/parcels/add'
    | '/profile/edit'
    | '/address/'
    | '/parcels/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/parcels/add'
    | '/profile/edit'
    | '/address'
    | '/parcels'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_menu'
    | '/_authenticated/onboarding'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/_authenticated/_menu/parcels/add'
    | '/_authenticated/_menu/profile/edit'
    | '/_authenticated/_menu/address/'
    | '/_authenticated/_menu/parcels/'
    | '/_authenticated/_menu/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_menu': {
      id: '/_authenticated/_menu'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMenuRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_menu/profile/': {
      id: '/_authenticated/_menu/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedMenuProfileIndexRouteImport
      parentRoute: typeof AuthenticatedMenuRouteRoute
    }
    '/_authenticated/_menu/parcels/': {
      id: '/_authenticated/_menu/parcels/'
      path: '/parcels'
      fullPath: '/parcels/'
      preLoaderRoute: typeof AuthenticatedMenuParcelsIndexRouteImport
      parentRoute: typeof AuthenticatedMenuRouteRoute
    }
    '/_authenticated/_menu/address/': {
      id: '/_authenticated/_menu/address/'
      path: '/address'
      fullPath: '/address/'
      preLoaderRoute: typeof AuthenticatedMenuAddressIndexRouteImport
      parentRoute: typeof AuthenticatedMenuRouteRoute
    }
    '/_authenticated/_menu/profile/edit': {
      id: '/_authenticated/_menu/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedMenuProfileEditRouteImport
      parentRoute: typeof AuthenticatedMenuRouteRoute
    }
    '/_authenticated/_menu/parcels/add': {
      id: '/_authenticated/_menu/parcels/add'
      path: '/parcels/add'
      fullPath: '/parcels/add'
      preLoaderRoute: typeof AuthenticatedMenuParcelsAddRouteImport
      parentRoute: typeof AuthenticatedMenuRouteRoute
    }
  }
}

interface AuthenticatedMenuRouteRouteChildren {
  AuthenticatedMenuParcelsAddRoute: typeof AuthenticatedMenuParcelsAddRoute
  AuthenticatedMenuProfileEditRoute: typeof AuthenticatedMenuProfileEditRoute
  AuthenticatedMenuAddressIndexRoute: typeof AuthenticatedMenuAddressIndexRoute
  AuthenticatedMenuParcelsIndexRoute: typeof AuthenticatedMenuParcelsIndexRoute
  AuthenticatedMenuProfileIndexRoute: typeof AuthenticatedMenuProfileIndexRoute
}

const AuthenticatedMenuRouteRouteChildren: AuthenticatedMenuRouteRouteChildren =
  {
    AuthenticatedMenuParcelsAddRoute: AuthenticatedMenuParcelsAddRoute,
    AuthenticatedMenuProfileEditRoute: AuthenticatedMenuProfileEditRoute,
    AuthenticatedMenuAddressIndexRoute: AuthenticatedMenuAddressIndexRoute,
    AuthenticatedMenuParcelsIndexRoute: AuthenticatedMenuParcelsIndexRoute,
    AuthenticatedMenuProfileIndexRoute: AuthenticatedMenuProfileIndexRoute,
  }

const AuthenticatedMenuRouteRouteWithChildren =
  AuthenticatedMenuRouteRoute._addFileChildren(
    AuthenticatedMenuRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMenuRouteRoute: typeof AuthenticatedMenuRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMenuRouteRoute: AuthenticatedMenuRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
